/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms */

var num1 = 1;
var num2 = 0;
var num3;
var sum = 0;
var t = 4000000; 


while(num1 < t){
	num3 = num1;
	num1 += num2;
	num2 = num3;

	if (num1 % 2 == 0){
		sum += num1;
	}
}

console.log(sum);